default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "db") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USERNAME", "favorite") %>
  password: <%= ENV.fetch("DB_PASSWORD", "password") %>

development:
  <<: *default
  database: favorite_sys_development

test:
  <<: *default
  database: favorite_sys_test

production:
  <<: *default
  database: favorite_sys_production
